POST http://localhost:5000/api/surveyor/signup
Content-Type: application/json

{
    "firstName": "Paul",
    "lastName": "Doe",
    "email": "paul.doe@gmail.com",
    "phoneNumber": "1234567890",
    "password": "password234",
    "residentialAddress": "123 Main St",
    "postalAddress": "PO Box 456",
    "role": "surveyor"
}
###
POST http://localhost:5000/api/surveyor/login
Content-Type: application/json

{
    "email": "paul.doe@gmail.com",
    "password": "password234"
}
###
POST http://localhost:5000/api/surveyor/logout
Content-Type: application/json
###

GET http://localhost:5000/api/surveyor/profile
Content-Type: application/json
###

GET http://localhost:5000/api/surveyor/authenticate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzA4ZDY1YmJlYmE2YjZhYzVkYTk1NiIsInJvbGUiOiJzdXJ2ZXlvciIsImVtYWlsIjoicGF1bC5kb2VAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiUGF1bCIsImlhdCI6MTc2NTAyODI3NiwiZXhwIjoxNzY1MDMwMDc2fQ.uoM6wMSDs0xcQ21JHCi41BaHmhfczpLd8hDKdsagNik
###
PUT http://localhost:5000/api/surveyor/identity-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzA4ZDY1YmJlYmE2YjZhYzVkYTk1NiIsInJvbGUiOiJzdXJ2ZXlvciIsImVtYWlsIjoicGF1bC5kb2VAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiUGF1bCIsImlhdCI6MTc2NTAyNTUwNywiZXhwIjoxNzY1MDI3MzA3fQ.1J-jSSWs4GNZMyuA3HBourKnnvfdn1oGtUe0K_2fWQc

{
    "profilePhoto": "",
    "IDphoto": "",
    "proofOfCertificate": ""
}
###
PUT http://localhost:5000/api/surveyor/profile
Content-Type: application/json

{
    "firstName": "Paul",
    "lastName": "Porter",
    "email": "paul.doe@gmail.com",
    "phoneNumber": "1234567890",
    "password": "password234",
    "residentialAddress": "122 Main St",
    "postalAddress": "PO Box 455",
    "role": "surveyor"
}
###

POST http://localhost:5000/api/surveyor/billing-info
Content-Type: application/json

{
    "firstName": "Paul",
    "lastName": "Porter",
    "country": "USA",
    "companyTitle": "Surveyor Inc",
    "city": "New York",
    "address": "123 Main St",
    "postCode": "10001",
    "email": "paul.doe@gmail.com",
    "phone": "1234567890"
}
###
PUT http://localhost:5000/api/surveyor/billing-info
Content-Type: application/json

{
    "firstName": "Paul",
    "lastName": "Porter",
    "country": "USA",
    "companyTitle": "Surveyor LLC",
    "city": "New York",
    "address": "124 Main St",
    "postCode": "10002",
    "email": "paul.doe@gmail.com",
    "phone": "1234567890"
}
###

POST http://localhost:5000/api/surveyor/complete-profile
Content-Type: application/json

{
    "tagline": "Experienced Surveyor",
    "responseTime": "24 hours",
    "country": "USA",
    "about": "I have over 10 years of experience in surveying.",
    "surveyorType": "Land Surveyor",
    "languages": [{"language": "English"}, {"language": "Spanish"}],
    "yearsOfExperience": 10,
    "projectDetails": "Completed over 100 projects successfully.",
    "fileFormat": [{"fileType": "PDF"}, {"fileType": "DWG"}],
    "softwares": [{"name": "AutoCAD"}, {"name": "GIS"}],
    "professionalCertifications":[
        {
            "certificateName": "Certified Surveyor"
        }
    ],
    "education": [
        {
            "title": "B.Sc. in Geomatics",
            "institutionName": "University of Surveying",
            "dateFrom": "2010-09-01",
            "dateTo": "2014-06-30",
            "description": "Studied various surveying techniques and technologies."
        }
    ]
}
###

GET http://localhost:5000/api/surveyor/assigned
Content-Type: application/json
###

GET http://localhost:5000/api/surveyor/disputes
Content-Type: application/json
###
PUT http://localhost:5000/api/surveyor/693040ff6654a7d819077752/accept
Content-Type: application/json
###
PUT http://localhost:5000/api/surveyor/693040ff6654a7d819077752/decline
Content-Type: application/json
###
Put http://localhost:5000/api/surveyor/693040ff6654a7d819077752/start
Content-Type: application/json
###
PUT http://localhost:5000/api/surveyor/693040ff6654a7d819077752/submit
Content-Type: application/json

{
    "workSubmission": {
        "deliveryNotes": "Survey completed successfully.",
        "files": [
            {
                "fileName": "survey_report.pdf",
                "fileUrl": "http://example.com/survey_report.pdf"
            }
        ]
    }
}
###
