POST http://localhost:5000/api/signup
Content-Type: application/json

{
    "firstName": "Peter",
    "lastName": "Pan",
    "email": "peterpan@example.com",
    "phoneNumber": "1234567890",
    "password": "SecurePeterPass123",
    "residentialAddress": "123 Main St, Anytown, USA",
    "postalAddress": "PO Box 456, Anytown, USA",
    "role": "admin"
}
###

POST http://localhost:5000/api/signin
Content-Type: application/json

{
    "email": "peterpan@example.com",
    "password": "SecurePeterPass123"
}
###

PUT http://localhost:5000/api/profile
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZmE2MmYyYmJlZjhjYTA3NTIxMWJmNCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NjEyNDAwODIsImV4cCI6MTc2MTI3NjA4Mn0.q_mD48e5ppG-0gsrHwYjITA_OnA4u3Qgjjv0ROelpL4

{
    "firstName": "Johnathan",
    "lastName": "Doe",
    "phoneNumber": "0987654321",
    "residentialAddress": "456 Elm St, Othertown, USA"
}
###

GET http://localhost:5000/api/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZmE2MmYyYmJlZjhjYTA3NTIxMWJmNCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NjEyNDAwODIsImV4cCI6MTc2MTI3NjA4Mn0.q_mD48e5ppG-0gsrHwYjITA_OnA4u3Qgjjv0ROelpL4
###

POST http://localhost:5000/api/billing-info
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZmE2MmYyYmJlZjhjYTA3NTIxMWJmNCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NjEyNDAwODIsImV4cCI6MTc2MTI3NjA4Mn0.q_mD48e5ppG-0gsrHwYjITA_OnA4u3Qgjjv0ROelpL4

{
    "firstName": "Johnathan",
    "lastName": "Doe",
    "country": "USA",
    "companyTitle": "Software Engineer",
    "city": "Othertown",
    "address": "456 Elm St, Othertown, USA",
    "postCode": "67890",
    "email": "johndoe@example.com",
    "phone": "0987654321"
}
###

PUT http://localhost:5000/api/billing-info
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZmE2MmYyYmJlZjhjYTA3NTIxMWJmNCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NjEyNDAwODIsImV4cCI6MTc2MTI3NjA4Mn0.q_mD48e5ppG-0gsrHwYjITA_OnA4u3Qgjjv0ROelpL4

{
    "firstName": "Johnathan",
    "lastName": "Doe",
    "country": "USA",
    "companyTitle": "Senior Software Engineer",
    "city": "Othertown",
    "address": "789 Pine St, Newtown, USA",
    "postCode": "67890",
    "email": "",
    "phone": "0987654321"
}
###

POST http://localhost:5000/api/signout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZmE2MmYyYmJlZjhjYTA3NTIxMWJmNCIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NjEyNDU2NTIsImV4cCI6MTc2MTI4MTY1Mn0.YmP5UXmvhLHO9vMVgM_VynYb_oar_da5IsjSdOys_SM
###